- hosts: PSwitches, PESwitches, Routers
  connection: local
  vars:
    vrf_name: myVRF
    route_target: "456:1"
    route_distinguisher: 10.9.9.9:123
  tasks:
  - name: create new vrf
    ios_vrf:
      name: "{{ vrf_name }}"
      rd: "{{ route_distinguisher }}"
      route_import:
        - "{{ route_target }}"
      route_export:
        - "{{ route_target }}"
  - name: create vrf bgp redistribution
    ios_config:
      parents: router bgp 65000
      lines:
        - "address-family ipv4 vrf {{ vrf_name }}"
        - "redistribute connected"