- hosts: PSwitches, PESwitches
  connection: local
  tasks:
  - name: create new vrf on switches
    ios_vrf:
      name: myVRF
      rd: 10.9.9.9:123
      route_import:
        - "456:1"
      route_export:
        - "456:1"
  - name: create vrf bgp redistribution
    ios_config:
      parents: router bgp 65000
      lines:
        - address-family ipv4 vrf myVRF
        - redistribute connected